########################################
# Python Runtime
########################################

PYTHON_EXECUTABLE=

MINIMUM_PYTHON_VERSION=3.12

AUTO_DISCOVER_PYTHON=true

########################################
# Virtual Environment
########################################

USE_VENV=false

VENV_DIRECTORY=.venv

########################################
# Validation
########################################

VALIDATE_PYTHON_RUNTIME=true

VALIDATE_PYTHON_PACKAGES=true

########################################
# Logging
########################################

PYTHON_LOG_LEVEL=INFO